apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing-deployment
spec:
  selector:
    matchLabels:
      app: syncthing
  replicas: 1
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
      - name: syncthing
        image: syncthing/syncthing
        ports:
        - containerPort: 8384
          name: http
        - containerPort: 22000
          name: sync
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
spec:
  selector:
    app: syncthing
  ports:
    - protocol: TCP
      port: 8384
      targetPort: 8384
      name: http
    - protocol: TCP
      port: 22000
      targetPort: 22000
      name: sync
  type: LoadBalancer
